kolmodin/binary

src/Data/Binary/Class.hs
The old Binary instance for Char used Data.Char.chr, which calls error
if given an invalid code point. The instance is modified to call fail
instead of error on invalid code points, which is total (within the Get
Monad). Calls to error inside Get will escape decodeOrFail.
This was discovered in `Cabal-1.22.0.0`, because we lean pretty heavily on `binary` now.
=> Make get :: Get Char total

src/Data/Binary/Get/Internal.hs
`getByteString` exhibited quadratic behaviour -- a classic case of bad "appending".  This commit fixes it.
=> Linear `getByteString`

benchmarks/Get.hs, src/Data/Binary/Class.hs
Regarding #85.
The "roll" benchmarks in the get executable show the difference:
```
get roll
benchmarking roll/foldr
time                 547.4 ms   (537.8 ms .. 553.5 ms)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 549.4 ms   (547.2 ms .. 550.4 ms)
std dev              1.857 ms   (0.0 s .. 1.896 ms)
variance introduced by outliers: 19% (moderately inflated)
benchmarking roll/foldl'
time                 434.7 ms   (426.4 ms .. 443.1 ms)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 433.7 ms   (432.3 ms .. 434.7 ms)
std dev              1.472 ms   (0.0 s .. 1.696 ms)
variance introduced by outliers: 19% (moderately inflated)
```
The "Integer/decode" benchmark shows the actual decoding speed.
First the old implementation based on `foldr`:
```
get Integer/decode …
```
=> Optimize roll by using foldl' instead of foldr

src/Data/Binary/Class.hs
This is difficult change, as it will break `Cabal` which provides orphan instance.
=> Add Binary Version instance

src/Data/Binary.hs, src/Data/Binary/Class.hs, src/Data/Binary/Generic.hs
Consider:
{-# LANGUAGE DeriveGeneric #-}
module A where
import Data.Binary
import GHC.Generics
data T = T
() () () () () () () () () ()
() () () () () () () () () ()
() () () () () () () () () ()
() () () () () () () () () ()
() () () () () () () () () ()
() () () () () () () () () ()
() () () () () () () () () ()
() () () () () () () () () ()
() () () () () () () () () ()
() () () () () () () () () ()
deriving Generic
instance Binary T
Without this patch, on GHC 7.10.2, building this -O2 takes 6.7s.  With
this patch, it takes 1.7s.  Amazing.  (There are modest improvements
with other versions of GHC too.)
Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>
=> Split GBinary into GBinaryGet and GBinaryPut, speeds up compilation.

src/Data/Binary/Get/Internal.hs, src/Data/Binary/Put.hs
This avoids potential performance issues as well as
future proofing the code.
=> Canonicalise Monad instances

src/Data/Binary/Builder/Base.hs
This makes `binary` `-Wcompat`-clean for GHC 8.0
=> Define Semigroup instance for base>=4.9

binary.cabal, src/Data/Binary/Get/Internal.hs
This is the variant not introducing a dependency on http://hackage.haskell.org/package/fail
(see #103 for other variant)
=> Define MonadFail instance for Get Monad

src/Data/Binary/Class.hs
Otherwise we end up relying on dynamic dispatch here which has a rather
drastic effect on runtime. The code associated with these instances (especially 
the smaller tuples) isn't terribly large so this seems worthwhile.
=> Ensure that Binary instances for tuples are inlined

src/Data/Binary/Get/Internal.hs
My `b-tree` library seems to tickle a rather pathological behavior in
`binary`'s decoding logic, where `binary` will create many needless
copies of the input buffer by evaluating things of the form `B.concat
[B.empty, leftovers]`, where `leftovers` is large.
This resulted in runtimes of over two minutes when parsing a 50 MByte
file. With this fix run drops to less than 100 milliseconds.
=> [RFC] Get: Avoid needless copies of input

src/Data/Binary/Class.hs
This adds simple `Binary` instances for:
1. The newtype wrappers in `Data.Monoid`
2. The datatypes brought into `base` (from `semigroups`) in `base-4.9`:
* The datatypes in `Data.Semigroup`
* `Data.List.NonEmpty.NonEmpty`
Fixes #107.
/cc @hvr and @phadej (who currently defines some of these instances in `binary-orphans`)
=> Add Binary instances for datatypes in Data.Monoid/Data.Semigroup

binary.cabal, src/Data/Binary/FloatCast.hs, src/Data/Binary/Get.hs, src/Data/Binary/Put.hs, tests/QC.hs
This PR introduces get/put functions for floats and doubles. It also includes round trip tests for these functions.
You will notice that I added a new dependency: `reinterpret-cast`. This is for fast and convenient cast between words and floating point numbers.
The package `reinterpret-cast` only depends on `array` and `base`, packages `binary` already depend on. If this is a problem, we can have our own implementation, but I think it is better to depend on `reinterpret-cast`. If anybody knows a better way to cast numbers, it can be implemented in `reinterpret-cast`. Then `binary` will be passively improved, and so will be a greater set of packages. If some day `base` includes a function to cast words to/from floating point numbers (efficiently), we can drop the dependency on …
=> Implementation of get/put functions for floats/doubles

.travis.yml
Seems that older version of cabal-install doesn't correctly handle the constraint "cabal-version".
Attempting to fix the problem by bumping the cabal-install version.
=> [travis-ci] Fix build breakage

src/Data/Binary/Class.hs
With the changes in https://phabricator.haskell.org/D3257, GHC HEAD will emit a warning about the `put` definition on `KindRep`s, as it will now correctly bring in `KindRep`'s `COMPLETE` set of patterns into scope and detect that the wildcard pattern is redundant (see [here](https://phabricator.haskell.org/harbormaster/build/22348/) for an example where the build failed because of this). This removes the wildcard pattern to make GHC HEAD build again with `-Werror`.
=> Remove redundant pattern-match warning when built with GHC 8.2

src/Data/Binary/Class.hs
The module `Data.Functor.Identity` was added in `base-4.8.0.0`. Using CPP conditionals, I added a `Binary` instance for the `Identity` type.
Thanks.
=> Add Binary instance for Identity, from base-4.8.0.0

src/Data/Binary/Class.hs, src/Data/Binary/Generic.hs
Due to a bug in ghc, some unused imports do not yield warnings.
This commit will remove such unused imports in preparation for
the ghc bug fix (see https://ghc.haskell.org/trac/ghc/ticket/13064).
=> Remove unused imports.

src/Data/Binary/Class.hs
Brought up [here](https://cardano.org/wp-content/uploads/2018/08/report.pdf#%5B%7B%22num%22%3A12%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C62.692913386%2C597.699302373%2C0%5D).
Existing behaviour:
```haskell
ghci> runGetOrFail (get :: Get (NonEmpty Word)) (encode ([]:: [Word]))
Right ("",8,*** Exception: NonEmpty.fromList: empty list
```
New behaviour:
```haskell
ghci> runGetOrFail (get :: Get (NonEmpty Word)) (encode ([]:: [Word]))
Left ("",8,"NonEmpty is empty!")
```
=> 'Binary (NonEmpty a)' should 'fail' on empty lists

src/Data/Binary.hs, src/Data/Binary/Class.hs, src/Data/Binary/Get.hs, src/Data/Binary/Get/Internal.hs
* Use the standard `@since` notation (since it plays well with
re-exports in other packages)
* Use `@ ... @` for monospacing things that aren't identifiers
* Qualify some linked identifiers (so that they actually link)
=> Haddock markup fixes

src/Data/Binary/Class.hs
The clause will be rendered redundant by [GHC MR 963](https://gitlab.haskell.org/ghc/ghc/merge_requests/963).
=> Remove a redundant catch-all clause

.travis.yml, binary.cabal, tests/QC.hs
Travis keeps breaking due to its very fragile build script.
Switching to an approch which I hope will be more robust.
Only use recent version of cabal when building for all GHC versions.
This means we no longer test older cabal install binaries.
cabal-install is unable to come up with a build plan for the tests and
benchmarks. The problem seems to be that building binary's
tests/benchmarks requires having binary, which is what we're trying to
build. Cabal doesn't seem to separate the lib/tests/benchmarks into
distinct build units, so it fails to come up with a plan.
To work around this, when building on travis, we rename the binary
library. With a new name, cabal can find a plan and run the tests.
=> Make Travis build again.

src/Data/Binary/FloatCast.hs
They come with base and do not allocate in the average case.
Fixes https://github.com/kolmodin/binary/issues/137.
=> Use bases built-in float/word32 and double/word64 casts

src/Data/Binary/Get.hs
This is a companion to https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4492.
I'm not sure why the second-to-top commit isn't already merged, as ghc HEAD relies on it.
CC @bgamari
=> Use unsafe shifts from base rather than hand-rolling

src/Data/Binary/Class.hs
Corresponding GHC MR:
https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4945
=> Remove instance for Data.Semigroup.Option for GHC >= 9.2

binary.cabal, src/Data/Binary/Class.hs
* Set `default-language: Haskell2010`, otherwise GHC 9.2 will compile the package as GHC2021, which will break due to a Safe Haskell error. See GHC #19631.
* Add support for BoxedRep.
=> Changes for GHC 9.2.1

binary.cabal, changelog.md
This is the version that will ship with 9.2.1; it would be appreciated if you could release this as-is.
=> Bump version to 0.8.9.0

src/Data/Binary/Get/Internal.hs
Since many is recursive ghc will never inline it. Even if we mark as INLINE.
However ghc will complain if we compile with core lint enabled.
So we just mark it as INLINEABLE instead.
=> Mark many in Alternative instance as INLINEABLE

src/Data/Binary/Class.hs
This commit partially addresses #69, reducing user surprise by the non-round-tripping behavior of the Float and Double instances.
It is unfortunate that the following Haddock issue pushes typeclass instance documentation to be side notes, but at least the currently-added typeclass documentation is still visible on the resulting Haddock page.
https://github.com/haskell/haddock/issues/300
=> Added comments for Float and Double instances

src/Data/Binary/Class.hs
See https://github.com/haskell/core-libraries-committee/issues/167
This is, of course, a bit speculative at the moment, but given that the change does not involve CPP, it should not hurt to merge it anyways.
CC @bgamari
=> Future-proof against potential Prelude.foldl'
